/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and readiness
         * @description Answers from the process itself without consulting any store, so it has
         *     no failure response. A failure is the connection being refused.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every service with span metrics, worst health first */
        get: operations["listServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One service, with pods, dependencies, resources and failing traces */
        get: operations["getService"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{name}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent log lines for a service */
        get: operations["getServiceLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services/{name}/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent traces for a service */
        get: operations["getServiceTraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces/{traceID}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every log line carrying a trace id, across services
         * @description The pivot the product rests on. The id lives in the log body rather
         *     than structured metadata, because Alloy collects container stdout and
         *     Loki never sees an OTLP TraceId field.
         */
        get: operations["getTraceLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the join key is intact */
        get: operations["getDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 16 or 32 lower-case hexadecimal characters. */
        TraceId: string;
        Error: {
            error: string;
            hint?: string;
        };
        /**
         * @description unknown means no spans in the window, which is not the same as spans
         *     that all succeeded.
         * @enum {string}
         */
        HealthStatus: "healthy" | "warning" | "critical" | "unknown";
        Health: {
            status: components["schemas"]["HealthStatus"];
            /** @description Why the status is what it is. Present whenever the status is not healthy. */
            reasons?: string[];
        };
        Pod: {
            name: string;
            phase: string;
            ready: boolean;
            restarts: number;
            node?: string;
        };
        Workload: {
            namespace: string;
            kind: string;
            name: string;
            desired: number;
            ready: number;
            restarts: number;
            pods?: components["schemas"]["Pod"][];
        };
        Service: {
            name: string;
            namespace: string;
            health: components["schemas"]["Health"];
            /** @description Requests per second. */
            requestRate: number;
            /** @description Failing requests as a ratio between 0 and 1. */
            errorRatio: number;
            p95Millis: number;
            sparkline?: number[];
            workload?: components["schemas"]["Workload"];
        };
        ServicesResponse: {
            services: components["schemas"]["Service"][];
            /** @description The query window, expressed as a Go duration. */
            window: string;
        };
        Edge: {
            client: string;
            server: string;
            requestRate: number;
            errorRatio: number;
        };
        PodUsage: {
            cpuMillis: number;
            memBytes: number;
        };
        TraceSummary: {
            traceId: components["schemas"]["TraceId"];
            rootServiceName?: string;
            rootTraceName?: string;
            durationMillis?: number;
            startTimeUnixNano?: string;
        };
        LogLine: {
            /** Format: date-time */
            timestamp: string;
            line: string;
            service: string;
            pod?: string;
        };
        ServiceDetail: {
            name: string;
            namespace: string;
            health: components["schemas"]["Health"];
            requestRate: number;
            errorRatio: number;
            p95Millis: number;
            workload?: components["schemas"]["Workload"];
            /** @description Usage per pod, keyed by pod name. */
            resources?: {
                [key: string]: components["schemas"]["PodUsage"];
            };
            inbound: components["schemas"]["Edge"][];
            outbound: components["schemas"]["Edge"][];
            errorTraces: components["schemas"]["TraceSummary"][];
            /** @description Deep links into Grafana's bundled Drilldown apps. */
            links: {
                [key: string]: string;
            };
            window: string;
        };
        ServiceLogsResponse: {
            service: string;
            lines: components["schemas"]["LogLine"][];
        };
        ServiceTracesResponse: {
            service: string;
            traces: components["schemas"]["TraceSummary"][];
        };
        TraceLogsResponse: {
            traceId: components["schemas"]["TraceId"];
            lines: components["schemas"]["LogLine"][];
        };
        Check: {
            name: string;
            /** @enum {string} */
            status: "pass" | "warn" | "fail";
            detail: string;
            hint?: string;
        };
        DiagnosticsResponse: {
            checks: components["schemas"]["Check"][];
            /** Format: date-time */
            checkedAt: string;
        };
    };
    responses: never;
    parameters: {
        /** @description The service name, which equals the Deployment name. */
        ServiceName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    listServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The services list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicesResponse"];
                };
            };
            /** @description The metrics store could not be queried. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getService: {
        parameters: {
            query?: {
                /** @description Disambiguates a service name that appears in more than one namespace. */
                namespace?: string;
            };
            header?: never;
            path: {
                /** @description The service name, which equals the Deployment name. */
                name: components["parameters"]["ServiceName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceDetail"];
                };
            };
            /** @description No service name was given. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No span metrics for that service in the window. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An upstream store could not be queried. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getServiceLogs: {
        parameters: {
            query?: {
                /** @description Narrows to this service's view of one trace. */
                traceId?: components["schemas"]["TraceId"];
            };
            header?: never;
            path: {
                /** @description The service name, which equals the Deployment name. */
                name: components["parameters"]["ServiceName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log lines, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceLogsResponse"];
                };
            };
            /** @description An upstream store could not be queried. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getServiceTraces: {
        parameters: {
            query?: {
                /** @description Set to error to return only failing traces. */
                status?: "error";
            };
            header?: never;
            path: {
                /** @description The service name, which equals the Deployment name. */
                name: components["parameters"]["ServiceName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trace summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceTracesResponse"];
                };
            };
            /** @description An upstream store could not be queried. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTraceLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                traceID: components["schemas"]["TraceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log lines from every service the trace passed through. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceLogsResponse"];
                };
            };
            /** @description The id was not 16 or 32 hexadecimal characters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One check per line, whatever their status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsResponse"];
                };
            };
            /** @description An upstream store could not be queried. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
